### ISSUE TITLE
add support to use pattern in path

### ISSUE THREAD

**Issue by ctf0** [marcdomain/ignoreit#11]
is it possible to add support for patterns in paths to cover things like `/node_modules` & `node_modules` ?

this is mostly to avoid the ext adding the `node_modules` where the file already have `/node_modules`.

**Comment by marcdomain** [comment]
Thanks for spotting this. It will be fixed shortly.

**Comment by marcdomain** [comment]
Fixed https://github.com/marcdomain/ignoreit/pull/12
