### ISSUE TITLE
Error says the following:

### ISSUE THREAD

**Issue by waleedrana777** [marcdomain/ignoreit#20]
Error occurred: Error: ENOENT: no such file or directory, scandir '///e%3A/Data%20folder/Code%202023/MERN/React/firebase_auth_and_crud'

**Comment by marcdomain** [comment]
Kindly provide more context to the issue. What version of the extension are you using?

**Comment by waleedrana777** [comment]
VERSION
======
Released on
3/17/2020, 13:16:33
Last updated
6/10/2022, 13:37:14

I don't know there is some kind of path you are reading using vscode electron node js engine and it is giving me this error. It occurs in every project I open. The path in the error becomes according to the name of the project!

For example: 
![image](https://user-images.githubusercontent.com/37755440/185800172-0ccc7be7-03d8-4d9a-8c9f-ffcd4d8e4152.png)

Error occurred: Error: ENOENT: no such file or directory, scandir '///e%3A/Data%20folder/Code%202023/Firebase/customActionHandler/custom_action_handler'

There is no custom setting mentioned for the extension that could help me!

**Comment by marcdomain** [comment]
Thanks. I will look into it this evening and get back to you.

**Comment by marcdomain** [comment]
Fixed 🎉
