### ISSUE TITLE
kindly add support for User settings.json (global) in vscode

### ISSUE THREAD

**Issue by Fattylee** [marcdomain/ignoreit#4]
**What an awesome extension!**
can you support for global settings.json in vs code?
It would be a great option so that I won't have to add it to every new project.
thanks, brother.

**Comment by marcdomain** [comment]
The key-value pair that is added to the vscode setting.json is global. It's an action that needs to be done once, and it will be available for all projects workspace you open on vscode. 
You can try it out on another workspace. As long as the workspace contains a ".git", the extension works.
